### PR TITLE
Make it easier to mock *fuse.Server in tests

### PR DESCRIPTION
**Pull request by Jille**
By using an interface instead

### CODE REVIEW

**Comment by Jille** [comment]
Filed in Gerrit on request of Han-Wen.

@SnoozeThis https://review.gerrithub.io/c/hanwen/go-fuse/+/539828

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/9p362Xde5u0) I will wait until https://review.gerrithub.io/c/539828 is merged and then add a comment.

**Comment by hanwen** [comment]
Why do you want to mock the server for testing? What is wrong with mounting the file system and going through the kernel to issue FS operations?

**Comment by hanwen** [comment]
this change is not backward compatible.

**Pull request closed without merging**
