### PR TITLE
add Travis CI config

### PR DESCRIPTION
**Pull request by jmhodges**
Run the tests on every PR with the race detector enabled.

### CODE REVIEW

**Comment by jmhodges** [comment]
The tests all pass in Travis CI with this config enabled.

To finish this work, @hanwen, you just have to https://travis-ci.org/profile/hanwen and flip the switch.

You could also make it a requirement for any new PRs that the tests pass in Travis CI! A nice time saver.

**Comment by rfjakob** [comment]
Maybe you want to call `all.bash` instead of your own `go test` command line. Otherwise +1!

**Comment by jmhodges** [comment]
Hm, all.bash doesn't seem to include `nodefs` and similar in its race testing because it explicitly lists directories to test in. This current patch checks if everything is buildable with `go get` is more comprehensive in its race testing.

Maybe tacking the ./all.bash command on to the end?

**Comment by navytux** [comment]
This PR can be closed as .travis.yml was added as part of https://github.com/hanwen/go-fuse/pull/227 (commit d17d1e6d71).

However for Travis CI to actially be active, as https://github.com/hanwen/go-fuse/pull/178#issuecomment-318984132 says, @hanwen has to flip corresponding switch on https://travis-ci.org/profile/hanwen .

Hope this helps,
Kirill

**Comment by navytux** [comment]
Thanks. I confirm the travis now is active as it automatically created CI jobs for my new pull request (https://github.com/hanwen/go-fuse/pull/237). Thus we could probably close this pull request.

**Comment by navytux** [comment]
> Thus we could probably close this pull request.

Ping, @hanwen. Probably you missed the message here - this PR should be hopefully just closed.

**Pull request closed without merging**
