### PR TITLE
Fix conflict opcodes on linux and darwin

### PR DESCRIPTION
**Pull request by dsxack**
`CAP_SETXATTR_EXT,CAP_INIT_EXT,CAP_INIT_RESERVED` opcodes conflicts with
osxfuse `CAP_CASE_INSENSITIVE,CAP_VOL_RENAME,CAP_XTIMES` opcodes,
that's causing panic, so it should be moved into linux specific build.

It fixes https://github.com/hanwen/go-fuse/issues/493
Gerrit: https://review.gerrithub.io/c/hanwen/go-fuse/+/1171980

### CODE REVIEW

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/commit/aab5a0dd1b9eea289e9f0cda96a283baaa1b5d10

**Comment by EdSchouten** [comment]
Any chance you're going to cut a release that includes this fix?

**Comment by darthShadow** [comment]
Hi @hanwen, would it be possible to tag a new version with this fix included please?

**Comment by hanwen** [comment]
> Hi @hanwen, would it be possible to tag a new version with this fix included please?

Will look into it when I'm back, early Feb.

**Comment by hanwen** [comment]
I pushed a 2.5.0 tag.

**Pull request closed without merging**
