### PR TITLE
loopback: Use UtimesNano instead of Futimes

### PR DESCRIPTION
**Pull request by rfjakob**
Futimes() only takes microsecond resolution while the FUSE call
Utimens() wants nanosecond precision.

This is why UTIME_OMIT did not work - this change fixes issue #60.

### CODE REVIEW

**Comment by rfjakob** [comment]
The Futimens syscall is not implemented! Check out https://golang.org/pkg/syscall/

**Comment by hanwen** [comment]
yes, that's what I am saying. See fuse/syscall_linux.go

**Comment by rfjakob** [comment]
Wow, that looks scary. I will take a look!

**Comment by hanwen** [comment]
it is simpler than it looks on first glance; you'll figure it out :-)

I think the Go library code may /proc for compatibility with older kernels.

**Comment by rfjakob** [comment]
Interestingly, `futimens` is not a syscall. It is just a glibc function that wraps `utimensat`.

So I have implemented Futimens() just like glibc does it and now use that function in the Utimens() FUSE call.

**Comment by rfjakob** [comment]
There is UtimesNanoAt ( https://godoc.org/golang.org/x/sys/unix#UtimesNanoAt ) which looked promising for a moment, but it does not allow to pass a nil path.

**Comment by rfjakob** [comment]
Ok, I have moved `futimens` into nodefs/syscall.go and made it private.

**Pull request merged**
