### PR TITLE
fuse: allow filesystems to have precise control over data cache

### PR DESCRIPTION
**Pull request by navytux**
See https://lwn.net/ml/linux-fsdevel/20190315212556.9315-1-kirr%40nexedi.com/ for rationale and details.

### CODE REVIEW

**Comment by hanwen** [comment]
this should only be merged if the upstream kernel patch goes in, rigt?

**Comment by navytux** [comment]
Yes, that's why I put it with WIP prefix.

**Comment by navytux** [comment]
@hanwen, I was working my wcfs tests today which include checking OS cache state, and along the way fixed TestFopenKeepCache: https://github.com/hanwen/go-fuse/pull/274. That fix needed to disable CAP_AUTO_INVAL_DATA and it turned natural that we can already introduce that under halfway-precise behaviour under PreciseDataCacheControl mount option. This way this merge request should eventually contain only the last patch (reworked) after https://github.com/hanwen/go-fuse/pull/274/commits/6beba202 (part of TestFopenKeepCache fix) is hopefully merged.

**Comment by navytux** [comment]
( rebased over updated https://github.com/hanwen/go-fuse/pull/274 )

**Comment by navytux** [comment]
Kernel patch entered fuse.git#for-next:

https://git.kernel.org/pub/scm/linux/kernel/git/mszeredi/fuse.git/commit/?id=ad2ba64dd489
https://git.kernel.org/pub/scm/linux/kernel/git/mszeredi/fuse.git/log/?h=for-next

**Comment by navytux** [comment]
Rebased to master with renaming "precise" -> "explicit" and removed the "WIP" prefix as the kernel patch landed into fuse.git tree. Interdiff:

```diff
diff --git a/fuse/api.go b/fuse/api.go
index d0384a1..f07eb59 100644
--- a/fuse/api.go
+++ b/fuse/api.go
@@ -157,7 +157,7 @@ type MountOptions struct {
 
 	// If set, ask kernel not to do automatic data cache invalidation.
 	// The filesystem is fully responsible for invalidating data cache.
-	PreciseDataCacheControl bool
+	ExplicitDataCacheControl bool
 }
 
 // RawFileSystem is an interface close to the FUSE wire protocol.
diff --git a/fuse/opcode.go b/fuse/opcode.go
index 0dc34cb..b19221c 100644
--- a/fuse/opcode.go
+++ b/fuse/opcode.go
@@ -97,13 +97,13 @@ func doInit(server *Server, req *request) {
 
 
 	dataCacheMode := input.Flags & CAP_AUTO_INVAL_DATA
-	if server.opts.PreciseDataCacheControl {
-		// we don't want CAP_AUTO_INVAL_DATA even if we cannot go into fully precise mode
+	if server.opts.ExplicitDataCacheControl {
+		// we don't want CAP_AUTO_INVAL_DATA even if we cannot go into fully explicit mode
 		dataCacheMode = 0
 
-		precise := input.Flags & CAP_PRECISE_INVAL_DATA
-		if precise != 0 {
-			dataCacheMode = precise
+		explicit := input.Flags & CAP_EXPLICIT_INVAL_DATA
+		if explicit != 0 {
+			dataCacheMode = explicit
 		}
 	}
 	server.kernelSettings.Flags |= dataCacheMode
diff --git a/fuse/print.go b/fuse/print.go
index afec07a..4f7b6a3 100644
--- a/fuse/print.go
+++ b/fuse/print.go
@@ -45,7 +45,7 @@ var (
 		CAP_MAX_PAGES:           "MAX_PAGES",
 		CAP_CACHE_SYMLINKS:      "CACHE_SYMLINKS",
 		CAP_NO_OPENDIR_SUPPORT:  "NO_OPENDIR_SUPPORT",
-		CAP_PRECISE_INVAL_DATA: "PRECISE_INVAL_DATA",
+		CAP_EXPLICIT_INVAL_DATA: "EXPLICIT_INVAL_DATA",
 	}
 	releaseFlagNames = map[int64]string{
 		RELEASE_FLUSH: "FLUSH",
diff --git a/fuse/test/cache_test.go b/fuse/test/cache_test.go
index 4448d61..ee20746 100644
--- a/fuse/test/cache_test.go
+++ b/fuse/test/cache_test.go
@@ -48,7 +48,7 @@ func setupCacheTest(t *testing.T) (string, *pathfs.PathNodeFs, func()) {
 
 	mntOpts := &fuse.MountOptions{
 		// ask kernel not to invalidate file data automatically
-		PreciseDataCacheControl: true,
+		ExplicitDataCacheControl: true,
 
 		Debug: testutil.VerboseTest(),
 	}
diff --git a/fuse/types.go b/fuse/types.go
index 5e12e40..339487a 100644
--- a/fuse/types.go
+++ b/fuse/types.go
@@ -289,7 +289,7 @@ const (
 	CAP_MAX_PAGES           = (1 << 22)
 	CAP_CACHE_SYMLINKS      = (1 << 23)
 	CAP_NO_OPENDIR_SUPPORT  = (1 << 24)
-	CAP_PRECISE_INVAL_DATA = (1 << 25)
+	CAP_EXPLICIT_INVAL_DATA = (1 << 25)
 )
 
 type InitIn struct {
```

**Comment by navytux** [comment]
Thanks.

**Pull request merged**
