### PR TITLE
Add test for #115

### PR DESCRIPTION
**Pull request by ahl**
Let me know if you had something different in mind. I confirmed that this fails prior to my patch.

### CODE REVIEW

**Comment by hanwen** [comment]
looks almost like what I was thinking of, but I'd rather see a test of a public interface, ie. trying to access the mountpoint (eg os.Lstat), and veriifying that that works. You'd probably have to move the test into test/ to get acces to a working filesystem

**Comment by ahl** [comment]
I tried a different approach.

**Comment by hanwen** [comment]
yeah, that's more like it.
thanks!

**Comment by hanwen** [comment]
cherry picked as d5da28da3917f2d902497a36eca71d9e68183189

**Pull request closed without merging**
