### PR TITLE
Do not fork a new process to unmount if user is privileged

### PR DESCRIPTION
**Pull request by pooya**
The root user can issue the umount syscall and does not need the
fusermount binary. Therefore, it is not necessary to fork and exec a new
process just to run the umount binary.

Golang has a global lock held for forking (See exec_unix.go in the golang
source tree):
"Acquire the fork lock so that no other threads create new fds that are
not yet close-on-exec before we fork."

So it would be best if processes would refrain from forking
unnecessarily.

Signed-off-by: Shayan Pooya <shayan@arista.com>

### CODE REVIEW

**Comment by pooya** [comment]
My employer (Arista) has signed the CLA.
Thanks.

**Comment by hanwen** [comment]
the code looks fine. Is there a way you can add your Arista identity to your GH profile?

**Comment by pooya** [comment]
The email is now linked to my Github profile.

**Comment by hanwen** [comment]
I still can't see it; does it need some button to be clicked?

**Comment by pooya** [comment]
The membership should now be visible on my github profile.
Cheers.

**Pull request merged**
