### PR TITLE
fix nil fileEntry

### PR DESCRIPTION
**Pull request by liver**
on Create, after addNewChild fe(fileEntry) is nil value

### CODE REVIEW

**Comment by hanwen** [comment]
needs a test that repros the problem.

**Comment by liver** [comment]
accessing a property of an object that does not exist.
For NodeWriter interface, in the case of FileHandle is nil.

**Comment by hanwen** [comment]
needs a test that demonstrates the crash.

**Comment by hanwen** [comment]
Your test should create a file system, mount it, and then trigger the crash. I suspect that creating a file in an FS that doesn't use file handles might do the trick.

**Comment by liver** [comment]
Changed the test.
It seems to me that in this case, the test is superfluous.
I have not changed or added any functionality or logic.
Added a check for the existence of an object before accessing its property.

**Comment by hanwen** [comment]
why are you proposing this fix then?

**Comment by liver** [comment]
fix nil pointer dereference
check for existence of object

**Comment by liver** [comment]
Is there any chance of correction?

```
if fe != nil {
    out.Fh = uint64(fe.fh)
}
```

**Comment by hanwen** [comment]
I am still waiting for a test that demonstrates a crash in a filesystem without this fix. If you have a FS that doesn't work, it should be straightforward to distill that into a test.

**Pull request closed without merging**
